version: '3.8'
services:
  log-service-db:
    image: postgres
    restart: always
    ports:
      - '10007:5432'
    volumes:
      - ./scripts/bootstrap/init_event_store_db.sh:/docker-entrypoint-initdb.d/init_event_store_db.sh
      - ./scripts/bootstrap/init_projection_db.sh:/docker-entrypoint-initdb.d/init_projection_db.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - 10008:8080
